version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

  jobs:
    # download latest version from S3 to leverage notebook cache
    pre_build:
      - 'mkdir -p $HOME/.ploomber/stats/'
      - 'echo "version_check_enabled: false" >> $HOME/.ploomber/stats/config.yaml'
    # upload to S3
    post_build:
      - conda env export --no-build > environment.lock.yml
      - cat environment.lock.yml

conda:
  environment: doc/environment.lock.yml

sphinx:
  builder: html
  fail_on_warning: true
  configuration: doc/_config.yml
