version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

  jobs:
    # download latest version from S3 to leverage notebook cache
    pre_build:
      - aws configure set aws_access_key_id ${aws_access_key_id}
      - aws configure set aws_secret_access_key ${aws_secret_access_key}
      - aws s3 cp s3://jupysql-build-docs/${READTHEDOCS_VERSION} _readthedocs/.jupyter_cache/ --recursive
      - 'mkdir -p $HOME/.ploomber/stats/'
      - 'echo "version_check_enabled: false" >> $HOME/.ploomber/stats/config.yaml'
    # upload to S3
    post_build:
      - conda env export --no-build > environment.lock.yml
      - cat environment.lock.yml
      - aws s3 cp _readthedocs/.jupyter_cache/ s3://jupysql-build-docs/${READTHEDOCS_VERSION} --recursive

conda:
  environment: doc/environment.lock.yml

sphinx:
  builder: html
  fail_on_warning: true
