version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_build:
      - conda env export --no-build > environment.lock.yml
      - cat environment.lock.yml


conda:
  environment: doc/environment.lock.yml

sphinx:
  builder: html
  fail_on_warning: true
