# binder environment file
name: jupysql-binder

channels:
  - conda-forge

dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - pip
  - pip:
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    # required to open .md files as nbs
    # pinning it because recent versions give
    # trouble, I think it's because they migrated
    # to jupyterlab 4. We cannot use jupyterlab 4
    # because jupysql-plugin is not compatible
    - jupytext<1.15
    - jupyterlab<4
    - jupyter-server<2
    # jupysql
    - --editable .
    # 5.10 introduced an issue that hasn't been fixed
    # https://github.com/microsoft/azuredatastudio/issues/24443
    - traitlets<5.10.0
