name: CI - DB Integration - Live 

on:
  push:
    branches:
      - master
      - 'dev/**'
  pull_request:


jobs:
  check:
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: early
        name: Set default as run
        run: |
          status="run"
          echo "status=$status" >> $GITHUB_OUTPUT
        name: Check github repository
        if: ${{ github.repository }}!= 'ploomber/jupysql'
        run: |
          status="skip"
          echo "status=$status" >> $GITHUB_OUTPUT
  database-live-integration-test:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: check
    if: needs.check.outputs.status == 'run'
    steps:
      - uses: actions/checkout@v2
      - name: Check source PR
        if: ${{ github.repository }}!= 'ploomber/jupysql'
        run: exit 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:
          pip install ".[integration]"
      - name: Integration Test
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run:
          # Run the integration test by pytest marker
          pytest src/tests/integration --verbose --live
