name: CI - DB Integration - Live 

on:
  push:
    branches:
      - master
      - 'dev/**'
  pull_request:


jobs:
  database-live-integration-test:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:
          pip install ".[integration]"
      - name: Echo github.event.repository.name
        run:
          echo ${{ github.event.repository.name }}
      - name: Echo github.repository
        run:
          echo ${{ github.repository }}
      - name: Echo github.repository_owner
        run:
          echo ${{ github.repository_owner }}
      - name: Echo github.base_ref
        run:
          echo ${{ github.base_ref }}
      - name: Integration Test
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        if: ${{ github.repository }} == 'ploomber/jupysql'
        run:
          # Run the integration test by pytest marker
          pytest src/tests/integration --verbose --live
